project:
  type: book
  output-dir: docs

lang: pt-br

execute:
  echo: false
  message: false
  warning: false

toc: true
toc-depth: 4  
  
book:
  title: "Caderno Metodológico"
  subtitle: "Etapa de Modelagem e Avaliação em Massa"
  author: "Luiz Fernando Palin Droubi"
  date: today
  date-format: "MMMM, YYYY"
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 02_basico.qmd
    - 03_limpeza.qmd
    - 04_classificacao.qmd
    - 05_renda_krigada.qmd
    - 06_VUM2.qmd
    - 07_variaveis.qmd
    - 08_metricas.qmd
    - 09_ML.qmd
    - 10_lotes.qmd
    - 11_equacoes.qmd
    - 12_municipios.qmd
    - 99_conclusao.qmd
    - references.qmd
  appendices:
    - 98_apendice1.qmd
  page-footer: 
    left: "© 2026 UFSC"
    center: "![](img/Logo com RFB e UFSC.png){width=250px}"
  downloads: [pdf, epub]
  repo-url: https://github.com/LabFSG-UFSC/VRCIB_Cad_Metodologico_Estimacao/
  repo-actions: [edit]
  sharing: [twitter, facebook]

bibliography: references.bib
csl: ABNT_UFPR_2011-Mendeley.csl
link-citations: true

format:
  html:
    css: [styles.css, cover-style.css]
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: source

